### ISSUE TITLE
monitoring of geodb age

### ISSUE THREAD

**Issue by rptaylor** [cvmfs-contrib/cvmfs-servermon#16]
Hi @DrDaveD 
Considering the recent changes, use of license keys, and the license requirement to update every 30 days, would it be possible for cvmfs-servermon to also check the status of the geodb file and issue a warning if it is older than 30 days?

**Comment by DrDaveD** [comment]
I have also been thinking about that.  So far, however, cvmfs-servermon is designed to be able to run entirely on an server that's external from the stratum 1, reading only over the web interface.  So in order to follow that design, we would need to first add a web api to cvmfs-server.  So I think it should start with a cvmfs ticket to request that for cvmfs-server-2.8.

**Comment by rptaylor** [comment]
https://sft.its.cern.ch/jira/browse/CVM-1857

**Comment by DrDaveD** [comment]
Yes so this info has been available as "last_geodb_update" in repositories.json for quite a while now.  We just need somebody to add it to the monitor.  There is already a "geo" test.  It could easily be added to that.
